from __future__ import annotations
from typing import Protocol, Iterable, Optional
from ..model import Workspace, Thread

class ThreadRepo(Protocol):
    def get(self, thread_id: str) -> Optional[Thread]: ...
    def list(self, include_archived: bool = False) -> Iterable[Thread]: ...
    def upsert(self, t: Thread) -> None: ...
    def archive(self, thread_id: str, archived: bool = True) -> None: ...
    def save_workspace(self, ws: Workspace) -> None: ...
    def load_workspace(self) -> Workspace: ...
