from typing import Protocol
from .message import Message
from .transport import Handler

class Broker(Protocol):
    async def publish(self, msg: Message) -> None: ...
    async def emit(self, type: str, payload: dict, meta: dict | None = None) -> None: ...
    def route(self, pattern: str, handler: Handler) -> None: ...