from typing import Protocol

from parallel_you.model.threads import Thread
from filter_spec import FilterSpec

class Repo(Protocol):
    def list(self, FilterSpec) -> list[Thread]: ...
    def upsert(self, Thread) -> str: ...
    def get(self, str) -> Thread | None: ...
    def delete(self, str) -> bool: ...
    def clear(self, str) -> None: ...

